export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const GET_PROJECT_TASK_BY_ID = "GET_PROJECT_TASK_BY_ID";
export const UPDATE_PROJECT_TASK_BY_ID = "UPDATE_PROJECT_TASK_BY_ID";
